kind: Deployment
apiVersion: extensions/v1beta1 
metadata:
  name: simple-node-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sns
    spec:
      containers:
      - name: simple-node-server
        image: simple-node-server:v1
        ports:
        - containerPort: 8080
