kind: Deployment
apiVersion: extensions/v1beta1 
metadata:
  name: simple-node-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sns
    spec:
      containers:
      - name: simple-node-server
        image: simple-node-server:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: ""
        - name: DB_PORT
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value: ""
        - name: DB_PASSWD
          value: ""
